import React from 'react';
import { PluginTemplate } from '../types';
import { VstIcon, AuIcon, AaxIcon, StandaloneIcon, DownloadIcon } from './icons';

interface ExportFormat {
    name: string;
    description: string;
    extension: string;
    icon: React.ReactNode;
}

const exportFormats: ExportFormat[] = [
    { name: 'VST3', description: 'For Windows & macOS DAWs', extension: 'vst3', icon: <VstIcon /> },
    { name: 'Audio Unit (AU)', description: 'For macOS DAWs (Logic Pro)', extension: 'component', icon: <AuIcon /> },
    { name: 'AAX', description: 'For Pro Tools', extension: 'aaxplugin', icon: <AaxIcon /> },
    { name: 'Standalone', description: 'Runnable App (Win/Mac)', extension: 'exe', icon: <StandaloneIcon /> },
];

const ExportCard: React.FC<{ format: ExportFormat; onDownload: (format: ExportFormat) => void; }> = ({ format, onDownload }) => (
    <div className="bg-surface/80 backdrop-blur-sm rounded-lg p-5 flex flex-col justify-between border border-background hover:border-accent/50 transition-all group">
        <div>
            <div className="flex items-center space-x-4 mb-3">
                <div className="bg-background p-3 rounded-full group-hover:bg-accent/20 text-accent transition-colors">
                    {format.icon}
                </div>
                <div>
                    <h3 className="text-lg font-bold text-primary">{format.name}</h3>
                    <p className="text-sm text-secondary">{format.description}</p>
                </div>
            </div>
        </div>
        <button 
            onClick={() => onDownload(format)}
            className="mt-4 w-full flex items-center justify-center bg-surface text-primary font-semibold py-3 rounded-lg hover:bg-accent hover:text-primary transition-colors"
        >
            <DownloadIcon />
            Download
        </button>
    </div>
);

const ExportView: React.FC<{ project: PluginTemplate }> = ({ project }) => {
    
    const sanitizeFilename = (name: string) => {
        return name.replace(/[^a-z0-9_]/gi, '-').replace(/-+/g, '-').toLowerCase();
    };

    const handleDownload = (format: ExportFormat) => {
        const filename = `${sanitizeFilename(project.name)}.${format.extension}`;
        const dummyContent = `This is a dummy ${format.name} file for the plugin "${project.name}".\n\nGenerated by Amapiano AI.`;
        const blob = new Blob([dummyContent], { type: 'application/octet-stream' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="p-6 mb-4 bg-background/50 rounded-lg border border-surface animate-fade-in">
            <h3 className="text-xl font-bold text-primary mb-1">Build Successful!</h3>
            <p className="text-secondary mb-6">Your plugin is compiled and ready to export.</p>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                {exportFormats.map(format => (
                    <ExportCard key={format.name} format={format} onDownload={handleDownload} />
                ))}
            </div>
        </div>
    );
};

export default ExportView;
