

import React, { useState, useMemo } from 'react';
import { PluginTemplate, TemplateCategory } from '../types';
import { SearchIcon, DownloadIcon } from './icons';

const juceBoilerplate = `
/*
  ==============================================================================

    MyPlugin.cpp
    Generated by Amapiano AI

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"

//==============================================================================
MyPluginAudioProcessor::MyPluginAudioProcessor()
#ifndef JucePlugin_PreferredChannelConfigurations
     : AudioProcessor (BusesProperties()
                     #if ! JucePlugin_IsMidiEffect
                      #if ! JucePlugin_IsSynth
                       .withInput  ("Input",  juce::AudioChannelSet::stereo(), true)
                      #endif
                       .withOutput ("Output", juce::AudioChannelSet::stereo(), true)
                     #endif
                       )
#endif
{
    // Parameter initialization goes here
}

MyPluginAudioProcessor::~MyPluginAudioProcessor()
{
}

// ... more JUCE boilerplate
`;

const vintageTapeVerbWebAudioCode = `
class VintageTapeVerb {
    constructor(audioContext) {
        this.audioContext = audioContext;
        this.input = this.audioContext.createGain();
        this.output = this.audioContext.createGain();
        this.wet = this.audioContext.createGain();
        this.dry = this.audioContext.createGain();

        this.convolver = this.audioContext.createConvolver();
        this.waveShaper = this.audioContext.createWaveShaper();
        
        this.input.connect(this.dry);
        this.input.connect(this.waveShaper);
        this.waveShaper.connect(this.convolver);
        this.convolver.connect(this.wet);
        
        this.dry.connect(this.output);
        this.wet.connect(this.output);

        this._generateImpulseResponse(0.6); // Corresponds to 60% decay
        this.setParam('mix', 50);
        this.setParam('saturation', 40);
    }

    setParam(id, value) {
        const now = this.audioContext.currentTime;
        if (id === 'mix') {
            const mixValue = value / 100;
            this.wet.gain.linearRampToValueAtTime(mixValue, now + 0.01);
            this.dry.gain.linearRampToValueAtTime(1 - mixValue, now + 0.01);
        } else if (id === 'saturation') {
            this._setSaturation(value / 100);
        } else if (id === 'decay') {
            this._generateImpulseResponse(value / 100);
        }
    }

    _setSaturation(value) { // 0-1
        const amount = value * 100;
        const n_samples = 44100;
        const curve = new Float32Array(n_samples);
        const deg = Math.PI / 180;
        for (let i = 0; i < n_samples; ++i) {
          const x = i * 2 / n_samples - 1;
          curve[i] = (3 + amount) * x * 20 * deg / (Math.PI + amount * Math.abs(x));
        }
        this.waveShaper.curve = curve;
    }

    _generateImpulseResponse(decay = 0.6) { // decay 0-1
        const sampleRate = this.audioContext.sampleRate;
        const duration = 0.5 + decay * 2.5;
        const numSamples = sampleRate * duration;
        const impulse = this.audioContext.createBuffer(2, numSamples, sampleRate);
        for (let channel = 0; channel < 2; channel++) {
            const channelData = impulse.getChannelData(channel);
            for (let i = 0; i < numSamples; i++) {
                channelData[i] = (Math.random() * 2 - 1) * Math.pow(1 - i / numSamples, 2.5);
            }
        }
        this.convolver.buffer = impulse;
    }
}
`;

const ambientPadsWebAudioCode = `
class AmbientPadGenerator {
    constructor(audioContext) {
        this.audioContext = audioContext;
        // This is the final output node the engine will connect to.
        this.output = this.audioContext.createGain();
        // This is the bus where all internal oscillators will connect.
        this.instrumentBus = this.audioContext.createGain();
        this.oscillators = [];
        
        // Effects Chain
        this.filter = audioContext.createBiquadFilter();
        this.filter.type = 'lowpass';
        this.filter.frequency.value = 2000;

        this.chorusLFO = audioContext.createOscillator();
        this.chorusLFO.frequency.value = 0.2;
        this.chorusDelay = audioContext.createDelay(0.1);
        this.chorusDepth = audioContext.createGain();
        this.chorusDepth.gain.value = 0.005;

        this.chorusLFO.connect(this.chorusDepth);
        this.chorusDepth.connect(this.chorusDelay.delayTime);
        this.chorusLFO.start();

        // ** CORRECTED AUDIO ROUTING **
        // 1. Instrument output goes into the filter.
        this.instrumentBus.connect(this.filter);
        
        // 2. The filtered signal has two paths:
        //    a) A 'dry' path directly to the final output.
        this.filter.connect(this.output);
        //    b) A 'wet' path through the chorus effect.
        this.filter.connect(this.chorusDelay);
        
        // 3. The wet chorus path also connects to the final output, mixing with the dry signal.
        this.chorusDelay.connect(this.output);

        this.attackTime = 0.6;
        this.releaseTime = 0.8;
    }

    setParam(id, value) {
        if (id === 'attack') this.attackTime = (value / 100) * 5;
        if (id === 'release') this.releaseTime = (value / 100) * 5;
        if (id === 'chorus') this.chorusDepth.gain.value = (value / 100) * 0.02;
    }

    play(note, time) {
        const now = this.audioContext.currentTime;
        const osc = this.audioContext.createOscillator();
        osc.frequency.value = note;
        osc.type = 'sawtooth';

        const gainNode = this.audioContext.createGain();
        gainNode.gain.setValueAtTime(0, now);
        gainNode.gain.linearRampToValueAtTime(0.3, now + this.attackTime);
        
        osc.connect(gainNode);
        // Oscillators connect to the internal bus, NOT the final output directly.
        gainNode.connect(this.instrumentBus);
        osc.start(time);
        
        this.oscillators.push({osc, gainNode});
    }

    stopAll(time) {
        const now = this.audioContext.currentTime;
        this.oscillators.forEach(({ osc, gainNode }) => {
            gainNode.gain.cancelScheduledValues(now);
            gainNode.gain.setValueAtTime(gainNode.gain.value, now);
            gainNode.gain.linearRampToValueAtTime(0, now + this.releaseTime);
            osc.stop(now + this.releaseTime + 0.1);
        });
        this.oscillators = [];
    }
}
`;


const templatesData: PluginTemplate[] = [
    {
        id: 'amapiano-log-drum',
        name: 'Amapiano Log Drum',
        type: 'instrument',
        framework: 'JUCE',
        description: 'Authentic South African log drum with pitch glide and knock',
        tags: ['amapiano', 'drums', 'south-african', 'percussion'],
        parameters: [
            { id: 'pitch', name: 'Pitch', type: 'range', defaultValue: 60, min: 24, max: 96, step: 1 },
            { id: 'glide', name: 'Glide', type: 'range', defaultValue: 25, min: 0, max: 100, step: 1 },
            { id: 'knock', name: 'Knock', type: 'range', defaultValue: 50, min: 0, max: 100, step: 1 },
            { id: 'decay', name: 'Decay', type: 'range', defaultValue: 70, min: 10, max: 100, step: 1 },
        ],
        code: juceBoilerplate.replace('MyPlugin', 'AmapianoLogDrum'),
        signalChain: ['Synth'],
    },
    {
        id: 'piano-one',
        name: 'Piano One',
        type: 'instrument',
        framework: 'JUCE',
        description: 'Realistic acoustic piano with velocity layers and pedal',
        tags: ['piano', 'acoustic', 'realistic', 'sampled'],
        parameters: [
             { id: 'velocity', name: 'Velocity', type: 'range', defaultValue: 80, min: 0, max: 127, step: 1 },
             { id: 'reverb', name: 'Reverb', type: 'range', defaultValue: 30, min: 0, max: 100, step: 1 },
             { id: 'dynamics', name: 'Dynamics', type: 'range', defaultValue: 100, min: 0, max: 100, step: 1 },
        ],
        code: juceBoilerplate.replace('MyPlugin', 'PianoOne'),
        signalChain: ['Sampler', 'Reverb'],
    },
    {
        id: 'vintage-tape-verb',
        name: 'Vintage Tape Verb',
        type: 'effect',
        framework: 'Web Audio',
        description: 'A lush reverb effect that emulates classic tape machine saturation.',
        tags: ['reverb', 'tape', 'vintage', 'saturation'],
        parameters: [
             { id: 'mix', name: 'Mix', type: 'range', defaultValue: 50, min: 0, max: 100, step: 1, unit: '%', affects: 'Global' },
             { id: 'decay', name: 'Decay', type: 'range', defaultValue: 60, min: 0, max: 100, step: 1, unit: '%', affects: 'Reverb' },
             { id: 'saturation', name: 'Saturation', type: 'range', defaultValue: 40, min: 0, max: 100, step: 1, unit: '%', affects: 'Saturation' },
        ],
        code: vintageTapeVerbWebAudioCode,
        signalChain: ['Saturation', 'Reverb'],
    },
    {
        id: '808-sub-bass',
        name: '808 Sub Bass Synth',
        type: 'instrument',
        framework: 'JUCE',
        description: 'Powerful 808-style sub bass synthesizer with drive and tone shaping.',
        tags: ['808', 'bass', 'synth', 'hip-hop'],
        parameters: [
             { id: 'drive', name: 'Drive', type: 'range', defaultValue: 30, min: 0, max: 100, step: 1 },
             { id: 'tone', name: 'Tone', type: 'range', defaultValue: 50, min: 0, max: 100, step: 1 },
             { id: 'release', name: 'Release', type: 'range', defaultValue: 80, min: 0, max: 100, step: 1 },
        ],
        code: juceBoilerplate.replace('MyPlugin', 'SubBassSynth'),
        signalChain: ['Synth', 'Saturation'],
    },
    {
        id: 'channel-strip-pro',
        name: 'Channel Strip Pro',
        type: 'utility',
        framework: 'JUCE',
        description: 'All-in-one utility with EQ, compression, and gating for mixing.',
        tags: ['mixing', 'utility', 'eq', 'compressor'],
        parameters: [
             { id: 'compThreshold', name: 'Comp Thresh', type: 'range', defaultValue: -18, min: -60, max: 0, step: 1 },
             { id: 'compRatio', name: 'Comp Ratio', type: 'range', defaultValue: 4, min: 1, max: 20, step: 1 },
             { id: 'eqMidGain', name: 'Mid Gain', type: 'range', defaultValue: 0, min: -12, max: 12, step: 1 },
        ],
        code: juceBoilerplate.replace('MyPlugin', 'ChannelStripPro'),
        signalChain: ['EQ', 'Compressor', 'Gate'],
    },
     {
        id: 'ambient-pads',
        name: 'Ambient Pad Generator',
        type: 'instrument',
        framework: 'Web Audio',
        description: 'Create evolving, atmospheric soundscapes and pads with ease.',
        tags: ['ambient', 'synth', 'pads', 'soundscape'],
        parameters: [
             { id: 'attack', name: 'Attack', type: 'range', defaultValue: 60, min: 0, max: 100, step: 1, unit: '%', affects: 'Amp Env' },
             { id: 'release', name: 'Release', type: 'range', defaultValue: 80, min: 0, max: 100, step: 1, unit: '%', affects: 'Amp Env' },
             { id: 'chorus', name: 'Chorus', type: 'range', defaultValue: 40, min: 0, max: 100, step: 1, unit: '%', affects: 'Chorus' },
        ],
        code: ambientPadsWebAudioCode,
        signalChain: ['Synth', 'Chorus'],
    }
];

const FilterButton: React.FC<{ label: string; active: boolean; onClick: () => void; }> = ({ label, active, onClick }) => (
    <button onClick={onClick} className={`px-4 py-2 text-sm font-semibold rounded-full transition-colors ${active ? 'bg-accent text-white' : 'bg-surface text-secondary hover:bg-background'}`}>
        {label}
    </button>
);

const Tag: React.FC<{ children: React.ReactNode }> = ({ children }) => (
    <span className="bg-hot-pink/20 text-hot-pink text-xs font-medium px-2.5 py-1 rounded-full">{children}</span>
);

const TemplateCard: React.FC<{ template: PluginTemplate; onSelect: (template: PluginTemplate, source: 'template') => void; }> = ({ template, onSelect }) => (
    <div className="bg-surface/80 backdrop-blur-sm rounded-lg p-5 flex flex-col border border-background hover:border-accent/50 transition-all group hover:scale-105 hover:shadow-lg hover:shadow-accent-glow/20">
        <div className="flex-grow">
            <div className="flex items-center space-x-4 mb-3">
                 <div className="bg-background p-3 rounded-full group-hover:bg-accent/20 transition-colors">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-accent" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 19V6l12-3v13M9 19c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zm12-3c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2z" /></svg>
                 </div>
                 <div>
                    <h3 className="text-lg font-bold text-primary">{template.name}</h3>
                    <div className="flex items-center space-x-2 text-xs mt-1">
                        <span className="bg-background text-secondary px-2 py-0.5 rounded">{template.type}</span>
                        <span className="bg-background text-secondary px-2 py-0.5 rounded">{template.framework}</span>
                    </div>
                 </div>
            </div>
            <p className="text-secondary text-sm mb-4">{template.description}</p>
            <div className="flex flex-wrap gap-2">
                {template.tags.map(tag => <Tag key={tag}>{tag}</Tag>)}
            </div>
        </div>
         <button onClick={() => onSelect(template, 'template')} className="mt-6 w-full flex items-center justify-center bg-accent text-primary font-semibold py-3 rounded-lg hover:bg-accent-hover transition-colors">
            <DownloadIcon />
            Use Template
        </button>
    </div>
);


const TemplatesView: React.FC<{ onSelectTemplate: (template: PluginTemplate, source: 'template') => void; }> = ({ onSelectTemplate }) => {
    const [searchQuery, setSearchQuery] = useState('');
    const [activeFilter, setActiveFilter] = useState<'All' | TemplateCategory>('All');

    const filteredTemplates = useMemo(() => {
        return templatesData
            .filter(template => activeFilter === 'All' || template.type === activeFilter)
            .filter(template =>
                template.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
                template.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
                template.tags.some(tag => tag.toLowerCase().includes(searchQuery.toLowerCase()))
            );
    }, [searchQuery, activeFilter]);


    return (
        <div className="p-6">
            <div className="bg-surface/50 border border-background rounded-lg p-5 mb-6">
                <h2 className="text-xl font-bold text-primary">Unlimited VST Plugin Templates</h2>
                <p className="text-secondary mt-1">
                    Professional-grade templates covering every plugin type. From synthesizers to effects, mastering tools to creative processors.
                    <span className="text-accent-hover"> 20+ templates ready to use</span>, unlimited possibilities with AI generation.
                </p>
            </div>

            <div className="flex flex-col sm:flex-row items-center justify-between gap-4 mb-6">
                <div className="relative w-full sm:max-w-xs">
                    <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                        <SearchIcon />
                    </div>
                    <input
                        type="text"
                        placeholder="Search unlimited templates..."
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        className="w-full bg-surface/50 border border-background rounded-full py-2 pl-10 pr-4 text-primary placeholder-secondary focus:outline-none focus:ring-2 focus:ring-accent focus:border-transparent"
                    />
                </div>
                <div className="flex items-center space-x-2">
                    <FilterButton label="All" active={activeFilter === 'All'} onClick={() => setActiveFilter('All')} />
                    <FilterButton label="Instrument" active={activeFilter === 'instrument'} onClick={() => setActiveFilter('instrument')} />
                    <FilterButton label="Effect" active={activeFilter === 'effect'} onClick={() => setActiveFilter('effect')} />
                    <FilterButton label="Utility" active={activeFilter === 'utility'} onClick={() => setActiveFilter('utility')} />
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {filteredTemplates.map(template => (
                    <TemplateCard key={template.id} template={template} onSelect={onSelectTemplate} />
                ))}
            </div>
             {filteredTemplates.length === 0 && (
                <div className="col-span-full text-center py-12">
                    <h3 className="text-lg font-semibold text-primary">No Templates Found</h3>
                    <p className="text-secondary mt-1">Try adjusting your search or filter criteria.</p>
                </div>
            )}
        </div>
    );
};

export default TemplatesView;